# Generated by Django 4.2 on 2023-04-14 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaPhong', models.CharField(max_length=5)),
                ('TrangThai', models.CharField(max_length=50)),
                ('SoluongSV', models.IntegerField()),
                ('LoaiPhong', models.CharField(max_length=50)),
                ('Gia', models.IntegerField()),
                ('TenToaNha', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Phong',
            },
        ),
        migrations.CreateModel(
            name='QuanLi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaQuanLi', models.CharField(max_length=50)),
                ('HoTen', models.CharField(max_length=50)),
                ('NgaySinh', models.DateField()),
                ('SoDienThoai', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=100)),
                ('Role', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'QuanLi',
            },
        ),
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MSSV', models.CharField(max_length=50)),
                ('HoTen', models.CharField(max_length=50)),
                ('GioiTinh', models.BooleanField()),
                ('NgaySinh', models.DateField()),
                ('DiaChi', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('SoDienThoai', models.CharField(max_length=10)),
                ('MaPhong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.phong')),
            ],
            options={
                'db_table': 'SinhVien',
            },
        ),
        migrations.CreateModel(
            name='HopDong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NgayBatDau', models.DateField()),
                ('NgayKetThuc', models.DateField()),
                ('GiaTien', models.IntegerField()),
                ('TrangThaiThanhToan', models.BooleanField()),
                ('MSSV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sinhvien')),
                ('MaPhong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.phong')),
                ('MaQuanLi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.quanli')),
            ],
            options={
                'db_table': 'HopDong',
            },
        ),
    ]
